---
kubeEtcd:
  enabled: false # etcd port is not open
kubeProxy:
  enabled: false # kube-proxy port is not open
prometheus:
  prometheusSpec:
    # By default, Prometheus discovers PodMonitors and ServiceMonitors within its namespace,
    # that are labeled with the same release tag as the prometheus-operator release
    # Allow rules, serviceMonitors and podMonitors to be automaticaly discovered in any namespace
    # without filtering on labels
    podMonitorNamespaceSelector:
      matchLabels: {}
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchLabels: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
